project:
  type: website

website:
  title: "Abdul Wasay Zarbi"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: Home
      - href: about.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



