project:
  type: website

website:
  title: "Abdul Wasay Zarbi"
  description: "Portfolio – Data Analyst & Researcher"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Portfolio"
        href: portfolio.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true



