name: Quarto Publish (R)

on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Step 1: Check out your repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'

      # Step 3: Restore R environment from renv
      - name: Restore R packages
        run: Rscript -e 'install.packages("renv"); renv::restore()'

      # Step 4: Set up Quarto
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Step 5: Render Quarto site
      - name: Render Quarto site
        run: quarto render

      # Step 6: Publish site to GitHub Pages
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
