name: Quarto Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Set up Quarto
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # 3. Render the site
      - name: Render Site
        run: quarto render

      # 4. Publish to GitHub Pages
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
