name: Quarto Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - uses: actions/checkout@v4

      # 2. Setup Quarto
      - uses: quarto-dev/quarto-actions/setup@v2

      # 3. Install R packages your site needs
      - name: Install R packages
        run: |
          R -e "install.packages(c('tidyverse','knitr','rmarkdown'), repos='https://cran.rstudio.com')"

      # 4. Render the Quarto site
      - name: Render site
        run: quarto render

      # 5. Publish to GitHub Pages
      - name: Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
