name: Quarto Publish Debug

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup R and Install Packages
        run: |
          R -e "install.packages(c('tidyverse','knitr','rmarkdown'), repos='https://cran.rstudio.com')"

      - name: Show current directory and files
        run: |
          pwd
          ls -la
          ls -la */

      - name: Render Quarto site
        run: |
          quarto render
        continue-on-error: true  # Allows workflow to continue and show logs even if rendering fails

      - name: Publish to GitHub Pages
        if: success()  # Only runs if render succeeds
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
